//! Safe ownership for the versioned mono sample-rate adapter.
//!
//! Conversion state is prepared on the control plane and then used through a
//! bounded, allocation-free operation. The external adapter owns
//! libsamplerate; this crate exposes no libsamplerate types or constants.

use std::ffi::{CStr, c_char, c_int, c_void};
use std::fmt;
use std::mem::size_of;
use std::ptr::NonNull;

const ABI_VERSION: u32 = 1;
const CAPABILITY: &CStr = c"rptadv.samplerate";
const RESULT_OK: c_int = 0;
const MINIMUM_RATIO: f64 = 1.0 / 256.0;
const MAXIMUM_RATIO: f64 = 256.0;

#[repr(C)]
struct OpaqueConverter {
    _private: [u8; 0],
}

type Create = unsafe extern "C" fn(c_int, u32, *mut *mut OpaqueConverter) -> c_int;
type Reset = unsafe extern "C" fn(*mut OpaqueConverter) -> c_int;
type Process = unsafe extern "C" fn(
    *mut OpaqueConverter,
    *const f32,
    u32,
    *mut f32,
    u32,
    f64,
    *mut u32,
    *mut u32,
) -> c_int;
type Destroy = unsafe extern "C" fn(*mut OpaqueConverter);

#[repr(C)]
#[derive(Clone, Copy)]
struct Descriptor {
    struct_size: u32,
    abi_version: u32,
    capability_name: *const c_char,
    create: Option<Create>,
    reset: Option<Reset>,
    process: Option<Process>,
    destroy: Option<Destroy>,
}

/// Sample-rate adapter setup or processing failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SampleRateError {
    /// The supplied descriptor is incompatible with this client.
    IncompatibleAdapter,
    /// A ratio, buffer length, or returned frame count is invalid.
    InvalidArgument,
    /// libsamplerate rejected or failed the operation.
    Conversion,
    /// The requested capability is unsupported.
    Unsupported,
    /// The adapter returned an undocumented result code or null handle.
    AdapterFailure,
}

impl fmt::Display for SampleRateError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let message = match self {
            Self::IncompatibleAdapter => "incompatible sample-rate adapter",
            Self::InvalidArgument => "invalid sample-rate conversion argument",
            Self::Conversion => "sample-rate conversion failed",
            Self::Unsupported => "sample-rate capability is unsupported",
            Self::AdapterFailure => "sample-rate adapter returned an unknown failure",
        };
        formatter.write_str(message)
    }
}

impl std::error::Error for SampleRateError {}

/// Band-limited conversion quality.
#[repr(i32)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum Quality {
    /// Highest-quality band-limited sinc conversion.
    #[default]
    SincBest = 0,
    /// Medium-quality band-limited sinc conversion.
    SincMedium = 1,
    /// Fastest band-limited sinc conversion.
    SincFastest = 2,
}

/// Frame counts consumed and generated by one streaming call.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct ProcessResult {
    /// Input frames consumed from the front of the supplied slice.
    pub input_used: usize,
    /// Output frames written to the front of the supplied slice.
    pub output_generated: usize,
}

/// Validated function table for a process-loaded sample-rate adapter.
#[derive(Clone, Copy)]
pub struct SampleRateAdapter {
    functions: Functions,
}

#[derive(Clone, Copy)]
struct Functions {
    create: Create,
    process: Process,
    destroy: Destroy,
}

impl SampleRateAdapter {
    /// Validate a process-lifetime adapter descriptor and copy its functions.
    ///
    /// # Safety
    ///
    /// `descriptor` must point to a correctly aligned descriptor whose shared
    /// object and functions remain loaded while any returned converter exists.
    pub unsafe fn from_raw(descriptor: *const c_void) -> Result<Self, SampleRateError> {
        let pointer = NonNull::new(descriptor.cast_mut().cast::<Descriptor>())
            .ok_or(SampleRateError::IncompatibleAdapter)?;
        // SAFETY: the caller guarantees a readable descriptor header.
        let header = unsafe { pointer.as_ref() };
        if header.struct_size < size_of::<Descriptor>() as u32
            || header.abi_version != ABI_VERSION
            || header.capability_name.is_null()
        {
            return Err(SampleRateError::IncompatibleAdapter);
        }
        // SAFETY: the descriptor contract requires a valid static C string.
        let capability = unsafe { CStr::from_ptr(header.capability_name) };
        if capability != CAPABILITY {
            return Err(SampleRateError::IncompatibleAdapter);
        }
        let (Some(create), Some(_), Some(process), Some(destroy)) =
            (header.create, header.reset, header.process, header.destroy)
        else {
            return Err(SampleRateError::IncompatibleAdapter);
        };
        Ok(Self {
            functions: Functions {
                create,
                process,
                destroy,
            },
        })
    }

    /// Create one persistent mono converter.
    pub fn create(&self, quality: Quality) -> Result<Converter, SampleRateError> {
        let mut converter = std::ptr::null_mut();
        // SAFETY: validation requires the function and writable handle storage is supplied.
        let result = unsafe { (self.functions.create)(quality as c_int, 1, &mut converter) };
        if let Err(error) = map_result(result) {
            if let Some(converter) = NonNull::new(converter) {
                // SAFETY: A non-null partial handle belongs to this adapter.
                unsafe { (self.functions.destroy)(converter.as_ptr()) };
            }
            return Err(error);
        }
        Ok(Converter {
            functions: self.functions,
            converter: NonNull::new(converter).ok_or(SampleRateError::AdapterFailure)?,
        })
    }
}

/// Exclusively owned persistent mono converter.
pub struct Converter {
    functions: Functions,
    converter: NonNull<OpaqueConverter>,
}

// SAFETY: the adapter permits ownership transfer; mutable methods serialize
// every operation on the converter handle.
unsafe impl Send for Converter {}

impl Converter {
    /// Convert one bounded portion of a continuing normalized-F32 stream.
    ///
    /// A successful call may consume or generate zero frames while the sinc
    /// filter gathers history. Resubmit any input after `input_used` on the
    /// next call. The adapter does not flush an end-of-stream tail.
    pub fn process(
        &mut self,
        input: &[f32],
        output: &mut [f32],
        ratio: f64,
    ) -> Result<ProcessResult, SampleRateError> {
        if !ratio.is_finite() || !(MINIMUM_RATIO..=MAXIMUM_RATIO).contains(&ratio) {
            return Err(SampleRateError::InvalidArgument);
        }
        let input_frames = checked_frame_count(input.len())?;
        let output_capacity = checked_frame_count(output.len())?;
        let mut input_used = 0;
        let mut output_generated = 0;
        // SAFETY: the slices are valid for their declared bounds, Rust keeps
        // them disjoint, and this object serializes access to the converter.
        map_result(unsafe {
            (self.functions.process)(
                self.converter.as_ptr(),
                input.as_ptr(),
                input_frames,
                output.as_mut_ptr(),
                output_capacity,
                ratio,
                &mut input_used,
                &mut output_generated,
            )
        })?;
        if input_used > input_frames || output_generated > output_capacity {
            return Err(SampleRateError::AdapterFailure);
        }
        Ok(ProcessResult {
            input_used: input_used as usize,
            output_generated: output_generated as usize,
        })
    }
}

impl Drop for Converter {
    fn drop(&mut self) {
        // SAFETY: this object exclusively owns the live converter handle.
        unsafe { (self.functions.destroy)(self.converter.as_ptr()) };
    }
}

fn checked_frame_count(length: usize) -> Result<u32, SampleRateError> {
    u32::try_from(length).map_err(|_| SampleRateError::InvalidArgument)
}

fn map_result(result: c_int) -> Result<(), SampleRateError> {
    match result {
        RESULT_OK => Ok(()),
        -1 => Err(SampleRateError::InvalidArgument),
        -2 => Err(SampleRateError::Conversion),
        -3 => Err(SampleRateError::Unsupported),
        _ => Err(SampleRateError::AdapterFailure),
    }
}

#[cfg(test)]
mod tests;
