//! Safe ownership for the versioned mono sample-rate adapter.
//!
//! Conversion state is prepared on the control plane and then used through a
//! bounded, allocation-free operation. The external adapter owns
//! its conversion backend; no backend types cross this boundary.

use std::ffi::{CStr, c_char, c_int, c_void};
use std::fmt;
use std::mem::size_of;
use std::ptr::NonNull;

const ABI_VERSION: u32 = 2;
const CAPABILITY: &CStr = c"rptadv.samplerate";
const RESULT_OK: c_int = 0;

#[repr(C)]
struct OpaqueConverter {
    _private: [u8; 0],
}

type Create = unsafe extern "C" fn(u32, u32, u32, u32, *mut *mut OpaqueConverter) -> c_int;
type Reset = unsafe extern "C" fn(*mut OpaqueConverter) -> c_int;
type Process = unsafe extern "C" fn(
    *mut OpaqueConverter,
    *const f32,
    u32,
    *mut f32,
    u32,
    f64,
    *mut u32,
    *mut u32,
) -> c_int;
type Destroy = unsafe extern "C" fn(*mut OpaqueConverter);
type QueuedInput = unsafe extern "C" fn(*mut OpaqueConverter, *mut u32) -> c_int;

#[repr(C)]
#[derive(Clone, Copy)]
struct Descriptor {
    struct_size: u32,
    abi_version: u32,
    capability_name: *const c_char,
    create: Option<Create>,
    reset: Option<Reset>,
    process: Option<Process>,
    destroy: Option<Destroy>,
    queued_input: Option<QueuedInput>,
    converter_output_delay: Option<QueuedInput>,
}

/// Sample-rate adapter setup or processing failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SampleRateError {
    /// The supplied descriptor is incompatible with this client.
    IncompatibleAdapter,
    /// A ratio, buffer length, or returned frame count is invalid.
    InvalidArgument,
    /// The conversion backend rejected or failed the operation.
    Conversion,
    /// The requested capability is unsupported.
    Unsupported,
    /// The adapter returned an undocumented result code or null handle.
    AdapterFailure,
}

impl fmt::Display for SampleRateError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let message = match self {
            Self::IncompatibleAdapter => "incompatible sample-rate adapter",
            Self::InvalidArgument => "invalid sample-rate conversion argument",
            Self::Conversion => "sample-rate conversion failed",
            Self::Unsupported => "sample-rate capability is unsupported",
            Self::AdapterFailure => "sample-rate adapter returned an unknown failure",
        };
        formatter.write_str(message)
    }
}

impl std::error::Error for SampleRateError {}

/// Frame counts consumed and generated by one streaming call.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct ProcessResult {
    /// Input frames consumed from the front of the supplied slice.
    pub input_used: usize,
    /// Output frames written to the front of the supplied slice.
    pub output_generated: usize,
}

/// Validated function table for a process-loaded sample-rate adapter.
#[derive(Clone, Copy)]
pub struct SampleRateAdapter {
    functions: Functions,
}

#[derive(Clone, Copy)]
struct Functions {
    create: Create,
    process: Process,
    destroy: Destroy,
}

impl SampleRateAdapter {
    /// Validate a process-lifetime adapter descriptor and copy its functions.
    ///
    /// # Safety
    ///
    /// `descriptor` must point to a correctly aligned descriptor whose shared
    /// object and functions remain loaded while any returned converter exists.
    pub unsafe fn from_raw(descriptor: *const c_void) -> Result<Self, SampleRateError> {
        let pointer = NonNull::new(descriptor.cast_mut().cast::<Descriptor>())
            .ok_or(SampleRateError::IncompatibleAdapter)?;
        let raw = pointer.as_ptr();
        // SAFETY: read only the mandatory prefix before validating the full size.
        let (struct_size, abi_version) = unsafe {
            (
                std::ptr::addr_of!((*raw).struct_size).read(),
                std::ptr::addr_of!((*raw).abi_version).read(),
            )
        };
        if struct_size < size_of::<Descriptor>() as u32 || abi_version != ABI_VERSION {
            return Err(SampleRateError::IncompatibleAdapter);
        }
        // SAFETY: the compatible header declares the entire descriptor readable.
        let header = unsafe { pointer.as_ref() };
        if header.capability_name.is_null() {
            return Err(SampleRateError::IncompatibleAdapter);
        }
        // SAFETY: the descriptor contract requires a valid static C string.
        let capability = unsafe { CStr::from_ptr(header.capability_name) };
        if capability != CAPABILITY {
            return Err(SampleRateError::IncompatibleAdapter);
        }
        let (Some(create), Some(_), Some(process), Some(destroy), Some(_), Some(_)) = (
            header.create,
            header.reset,
            header.process,
            header.destroy,
            header.queued_input,
            header.converter_output_delay,
        ) else {
            return Err(SampleRateError::IncompatibleAdapter);
        };
        Ok(Self {
            functions: Functions {
                create,
                process,
                destroy,
            },
        })
    }

    /// Prepare one persistent mono converter with immutable rates and call bounds.
    pub fn create(
        &self,
        input_rate: u32,
        output_rate: u32,
        maximum_input: usize,
        maximum_output: usize,
    ) -> Result<Converter, SampleRateError> {
        if input_rate == 0 || output_rate == 0 || maximum_input == 0 || maximum_output == 0 {
            return Err(SampleRateError::InvalidArgument);
        }
        let input_bound = checked_frame_count(maximum_input)?;
        let output_bound = checked_frame_count(maximum_output)?;
        let mut converter = std::ptr::null_mut();
        // SAFETY: validation requires the function and writable handle storage is supplied.
        let result = unsafe {
            (self.functions.create)(
                input_rate,
                output_rate,
                input_bound,
                output_bound,
                &mut converter,
            )
        };
        if let Err(error) = map_result(result) {
            if let Some(converter) = NonNull::new(converter) {
                // SAFETY: A non-null partial handle belongs to this adapter.
                unsafe { (self.functions.destroy)(converter.as_ptr()) };
            }
            return Err(error);
        }
        Ok(Converter {
            functions: self.functions,
            converter: NonNull::new(converter).ok_or(SampleRateError::AdapterFailure)?,
            nominal_ratio: f64::from(output_rate) / f64::from(input_rate),
            maximum_input,
            maximum_output,
        })
    }
}

/// Exclusively owned persistent mono converter.
pub struct Converter {
    functions: Functions,
    converter: NonNull<OpaqueConverter>,
    nominal_ratio: f64,
    maximum_input: usize,
    maximum_output: usize,
}

// SAFETY: the adapter permits ownership transfer; mutable methods serialize
// every operation on the converter handle.
unsafe impl Send for Converter {}

impl Converter {
    /// Convert one bounded portion of a continuing normalized-F32 stream.
    ///
    /// A successful call may consume or generate zero frames while the FIR
    /// filter gathers history. Accepted input is adapter-owned, even before it
    /// produces output: resubmit only the suffix after `input_used`. Empty input
    /// drains available output without flushing the FIR tail. The absolute
    /// output/input ratio stays within 0.1% of the prepared nominal ratio.
    pub fn process(
        &mut self,
        input: &[f32],
        output: &mut [f32],
        ratio: f64,
    ) -> Result<ProcessResult, SampleRateError> {
        if !ratio.is_finite()
            || !(self.nominal_ratio * 0.999..=self.nominal_ratio * 1.001).contains(&ratio)
            || input.len() > self.maximum_input
            || output.len() > self.maximum_output
        {
            return Err(SampleRateError::InvalidArgument);
        }
        let input_frames = checked_frame_count(input.len())?;
        let output_capacity = checked_frame_count(output.len())?;
        let mut input_used = 0;
        let mut output_generated = 0;
        // SAFETY: the slices are valid for their declared bounds, Rust keeps
        // them disjoint, and this object serializes access to the converter.
        map_result(unsafe {
            (self.functions.process)(
                self.converter.as_ptr(),
                input.as_ptr(),
                input_frames,
                output.as_mut_ptr(),
                output_capacity,
                ratio,
                &mut input_used,
                &mut output_generated,
            )
        })?;
        if input_used > input_frames || output_generated > output_capacity {
            return Err(SampleRateError::AdapterFailure);
        }
        Ok(ProcessResult {
            input_used: input_used as usize,
            output_generated: output_generated as usize,
        })
    }
}

impl Drop for Converter {
    fn drop(&mut self) {
        // SAFETY: this object exclusively owns the live converter handle.
        unsafe { (self.functions.destroy)(self.converter.as_ptr()) };
    }
}

fn checked_frame_count(length: usize) -> Result<u32, SampleRateError> {
    u32::try_from(length).map_err(|_| SampleRateError::InvalidArgument)
}

fn map_result(result: c_int) -> Result<(), SampleRateError> {
    match result {
        RESULT_OK => Ok(()),
        -1 => Err(SampleRateError::InvalidArgument),
        -2 => Err(SampleRateError::Conversion),
        -3 => Err(SampleRateError::Unsupported),
        _ => Err(SampleRateError::AdapterFailure),
    }
}

#[cfg(test)]
mod tests;
