/** @file
 * @brief Transitional S16 compatibility sample-rate conversion.
 *
 * The established Asterisk-facing calls retain signed-16 buffers while their
 * current mono sinc path delegates normalized F32 conversion to the released
 * sample-rate adapter.  These S16 signatures are a compatibility boundary,
 * not a new internal PCM contract.
 */

#ifndef USBRADIOPLUS_DSP_H
#define USBRADIOPLUS_DSP_H

#include <stddef.h>
#include <stdint.h>

#define URP_APP_RPT_RATE_DEFAULT 8000

#define URP_RATE_LINK URP_APP_RPT_RATE_DEFAULT

#define URP_RATE_NATIVE 48000

#define URP_LINK_SAMPLES 160

/** Default 20 ms CM119 callback size at the fixed 48 kHz native rate. */
#define URP_NATIVE_SAMPLES 960U
/**
 * Largest native callback accepted by the current ASL compatibility adapters.
 *
 * The adapters declare this bound when they open their stream.  The renderer
 * never allocates from the audio path, so all callback workspaces use this
 * bound while each tick receives its actual frame count explicitly.
 */
#define URP_NATIVE_MAX_SAMPLES URP_NATIVE_SAMPLES
/** Maximum interleaved stereo samples in one bounded native callback. */
#define URP_NATIVE_STEREO_SAMPLES (URP_NATIVE_MAX_SAMPLES * 2U)

struct urp_src;

/** @brief Allocate a streaming converter and reusable conversion workspace.
 * @param converter Sinc quality selection from the shared sample-rate adapter.
 * @param channels Must be one; both native compatibility converters are mono.
 * @return Owned converter state, or NULL on invalid arguments or allocation failure.
 */
struct urp_src *urp_src_create(int converter, unsigned int channels);
/** @brief Release a converter and its input and output buffers.
 * @param src Streaming sample-rate converter.
 */
void urp_src_destroy(struct urp_src *src);
/** @brief Clear resampler history at a stream discontinuity.
 * @param src Streaming sample-rate converter.
 */
void urp_src_reset(struct urp_src *src);
/** @brief Preallocate conversion workspaces before native callback processing.
 * @param src Streaming sample-rate converter.
 * @param input_capacity Maximum input frames accepted by one conversion.
 * @param output_capacity Maximum output frames generated by one conversion.
 * @return Zero on success; a nonzero status if storage could not be allocated.
 */
int urp_src_reserve(struct urp_src *src, size_t input_capacity, size_t output_capacity);
/** @brief Convert through already reserved SRC workspaces without allocating.
 * @param src Converter prepared with urp_src_reserve().
 * @param input Input samples; the caller retains ownership.
 * @param input_count Number of input samples available.
 * @param output Destination sample buffer owned by the caller.
 * @param output_capacity Number of samples the output buffer can hold.
 * @param ratio Output/input sample-rate ratio.
 * @param input_used Receives the number of input samples consumed.
 * @param output_generated Receives the number of output samples produced.
 * @return Zero on success; a nonzero status when the prepared capacity is insufficient.
 *
 * This prepared native-callback API never calls realloc; a changed block size
 * must be handled by the control plane before rendering begins. The current
 * mono sinc path calls the released F32 adapter with these preallocated
 * workspaces, then quantizes only at this legacy S16 boundary.
 */
int urp_src_process_prepared(struct urp_src *src, const int16_t *input, size_t input_count,
			     int16_t *output, size_t output_capacity, double ratio,
			     size_t *input_used, size_t *output_generated);
/** @brief Convert a fixed-rate PCM block using only pre-reserved converter storage.
 * @param src Converter prepared with urp_src_reserve() for rate-changing paths.
 * @param input Input samples; the caller retains ownership.
 * @param input_count Number of input samples available.
 * @param input_rate Input sample rate in Hz.
 * @param output Destination sample buffer owned by the caller.
 * @param output_capacity Number of samples the output buffer can hold.
 * @param output_rate Output sample rate in Hz.
 * @param input_used Receives the number of input samples consumed.
 * @param output_generated Receives the number of output samples produced.
 * @return Zero on success; a nonzero status without allocating on insufficient capacity.
 */
int urp_rate_convert_prepared(struct urp_src *src, const int16_t *input, size_t input_count,
			      unsigned int input_rate, int16_t *output, size_t output_capacity,
			      unsigned int output_rate, size_t *input_used,
			      size_t *output_generated);

#endif

/** @name File-local and build-time constants
 * @{ */
/** @def URP_APP_RPT_RATE_DEFAULT
 * @brief Initial app_rpt sample rate in Hz.
 */
/** @def URP_RATE_LINK
 * @brief Reference app_rpt sample rate in Hz.
 */
/** @def URP_RATE_NATIVE
 * @brief CM119 native audio sample rate in Hz.
 */
/** @def URP_LINK_SAMPLES
 * @brief Samples in one reference app_rpt receive frame.
 */
/** @def URP_NATIVE_SAMPLES
 * @brief Samples in one native 20 ms audio frame.
 */
/** @} */
