name: Required quality

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  quality:
    uses: cpeter1207/USBRadioPlus-Workflows/.github/workflows/quality.yml@main
