name: Publish package-site files

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  site:
    uses: cpeter1207/USBRadioPlus-Workflows/.github/workflows/site.yml@main
